apiVersion: apps/v1
kind: Deployment
metadata:
  name: niafikra-inaya
  labels:
    app: niafikra-inaya
spec:
  replicas: 1
  # to prevent deadlock on claiming disks remove the old pod and create a new one
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: niafikra-inaya
  template:
    metadata:
      labels:
        app: niafikra-inaya
    spec:
      containers:
        - name:  inaya
          image: niafikra/inaya:2024_01_RC9
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: INAYA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: inaya-secret
                  key: db-username
            - name: INAYA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inaya-secret
                  key: db-password
            - name: INAYA_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: inaya-configmap
                  key: db-url
            - name: TZ
              value: "Africa/Dar_es_Salaam"
            - name: CATALINA_OPTS
              value: "-Xmx4000m -Xms1000m"
