apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inaya-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany is not working for auto provisitioning using storageclasses of GCP disks
  resources:
    requests:
      storage: 1G
  storageClassName: longhorn