apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: inaya-legacy
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bonifacechacha/learning-argocd.git
        revision: master
        directories:
          - path: k8/prod/instances/overlays/*
    - git:
        repoURL: https://github.com/bonifacechacha/learning-argocd.git
        revision: master
        directories:
          - path: k8/prod/shared/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bonifacechacha/learning-argocd.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
