apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: inaya-ssd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain