apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: inaya-ssd
provisioner: kubernetes.io/example
parameters:
  type: pd-standard
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain