apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inaya-ssd-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany is not working for auto provisitioning using storageclasses of GCP disks
  resources:
    requests:
      storage: 10G
  storageClassName: inaya-ssd