apiVersion: v1
kind: ConfigMap
metadata:
  name: inaya-configmap
data:
  db-url: 'jdbc:mysql://10.82.128.3:3306/test'
---
apiVersion: v1
kind: Secret
metadata:
  name: inaya-secret
type: Opaque
data:
  db-username: aW5heWE=
  db-password: TjFhZjFrcmE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inaya
  labels:
    app: inaya
spec:
  replicas: 1
  # to prevent deadlock on claiming disks remove the old pod and create a new one
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: inaya
  template:
    metadata:
      labels:
        app: inaya
    spec:
      containers:
        - name: inaya
          image: niafikra/inaya:2024_01_RC9
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 1024Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 250m
              memory: 4096Mi
              ephemeral-storage: 1Gi
          ports:
            - containerPort: 8080
          env:
            - name: INAYA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: inaya-secret
                  key: db-username
            - name: INAYA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inaya-secret
                  key: db-password
            - name: INAYA_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: inaya-configmap
                  key: db-url
            - name: TZ
              value: "Africa/Dar_es_Salaam"
            - name: CATALINA_OPTS
              value: "-Xmx4000m -Xms1000m"
          volumeMounts:
            - mountPath: /root/.inaya
              name: data
              readOnly: false
      imagePullSecrets:
        - name: docker-registry-credential
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: inaya-ssd-pvc
