resources:
  - ../../base

commonLabels:
  app: niafikra-inaya

namePrefix: niafikra-

configMapGenerator:
  - name: inaya-config
    envs:
      - config.properties

secretGenerator:
  - name: inaya-secret
    envs:
      - secret.properties