resources:
  - ../../base

commonLabels:
  app: pazia-inaya

namePrefix: pazia-

configMapGenerator:
  - name: inaya-config
    envs:
      - config.properties

secretGenerator:
  - name: inaya-secret
    envs:
      - secret.properties